### ISSUE TITLE
Research question

### ISSUE THREAD

**Issue by tomcrick** [tomcrick/SIGCSE2021#10]
R1: In Introduction (section 1.3) the authors say “_It aimed to provide insight into emerging policy and practice; impact on practitioners, institutions and thus students; how might this change the discipline as a result; and what might this mean for the next academic year and in the longer-term._”

I suppose that these are the research questions. For me, this study only measured the impact of moving to online LT&A on practitioners. Definitely, the impact on students and other questions were not addressed.

**Comment by tomcrick** [comment]
This is a fair comment...

**Comment by CathrynKnight** [comment]
Something like:

"The study aimed to answer the following questions:

* How did the perceptions of the rapid move to online LT&A differ between practitioners in CS and other disciplines?
* How did the perceptions of the rapid move online LT&A differ by CS practitioner setting?
* What are the key opportunities and challenges perceived by CS practitioners globally?

**Comment by tomcrick** [comment]
Also closed in commit c69b452441107697f11c575549eb8032d835ec54
