### ISSUE TITLE
What were the collected demographic data?

### ISSUE THREAD

**Issue by tomcrick** [tomcrick/SIGCSE2021#11]
R1: What were the collected demographic data? It is unclear.

According to the authors, the questions exploring respondents’ views of the changes used Likert and slider-scales. What were these questions? Which one of these questions were based on Likert and which one were based on the slider scale? How many positions were considered in these scales? Likert was 1-5, 0-9? It is also unclear.

**Comment by CathrynKnight** [comment]
christ ! Do they want a diary or a paper!?

Get rid of mention of slider scales - I think it solves it.

**Comment by tomcrick** [comment]
Closed with commit 77fb90c4ac0efc6c5b85cc2b3038174e81ccfa4f
