### ISSUE TITLE
Replicability

### ISSUE THREAD

**Issue by tomcrick** [tomcrick/SIGCSE2021#13]
R1: As the methods aren't clear, the study is not replicable.

R3: The results in this paper would be difficult to replicate due to the way in which respondents were solicited, and due to a lack of transparency about discretisation decisions made for the Chi-square analyses.

**Comment by tomcrick** [comment]
This would be impossible to do in a six-page paper...!

**Comment by tomcrick** [comment]
Will check again in final version (if accepted)

**Comment by CathrynKnight** [comment]
Sorry ! Didn't see this. Hopefully we have changed it enough to account for this.
