### ISSUE TITLE
Paper structure for an empirical study

### ISSUE THREAD

**Issue by tomcrick** [tomcrick/SIGCSE2021#14]
R2: The paper is not organized properly. This is an empirical study. An empirical study should follow certain standard paper organization practices. It should have clearly sections for Research Questions, Research Method (subjects, study design, data collection method, artifacts used, etc.), Analysis, Validity Threats, and Discussion. This makes the study easier to follow and replicate.

**Comment by CathrynKnight** [comment]
I think we follow this format? But could add research questions?

**Comment by tomcrick** [comment]
Closed in commit 886160eaafa8e7cebe3a59fdb8ed1dce43fe9c20
