### ISSUE TITLE
Cross-checking results for CS educators

### ISSUE THREAD

**Issue by tomcrick** [tomcrick/SIGCSE2021#17]
R3:

In 3.1 the paper says that
(1) computing educators "were confident that their students could access online LT&A", and
(2) italicised figures in Table 1 mean the category was *less* likely to agree with the provided statement than expected

The figures for access are italicised for the CS columns. At first I was confused how both these things could be true, but I realised that statement (1) refers to a comparison with non-CS educators, and statement (2) refers to the results of chi-square test. Does this mean the CS educators were more confident about access than their non-CS counterparts, but less confident than expected? It would be good if this was clarified.

**Comment by CathrynKnight** [comment]
I'm not sure about this - can you send me the paper? I don't know which version I have saved. Diolch

**Comment by CathrynKnight** [comment]
Its an error in the table (oops) For Table 1 - final row: "“I am confident that all of my students will be able to access the teaching and assessment that I make available online” it should be bold in column 1 & 2 and italicised in columns 3 & 4 (same as the ones above" not sure why I did that !

**Comment by tomcrick** [comment]
Robust reviewing eh?
